[project]
name = "criando-agentes-agno"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "agno>=2.2.6",
    "groq>=0.33.0",
    "python-dotenv>=1.2.1",
    "tavily-python>=0.7.13",
]
